### ISSUE TITLE
Connect package functions to Shiny app

### ISSUE THREAD

**Issue by wleoncio** [SystemsBiologist/CellMigRation#64]
# Reference

CellMigRation_GUI_outline.pdf (private file)

# Subtasks

- [x] Add "Front page" functions (PDF pages 1-2)
- [x] Add "Second page" functions (PDF pages 3-4)
- [x] Add "Third page" UI (PDF page 5)
- [x] Add "Third page" functions (PDF page 6)
- [x] Add "Fourth page" UI (PDF pages 7 and 9)
- [ ] Add "Fourth page" functions (PDF page 10)

# App availability

- Development version: [shiny-page-4](https://github.com/ocbe-uio/cellmigRation/tree/shiny-page-4) branch
- Deployed version (for testing until delivery): https://ocbe.shinyapps.io/CellMigRation/

**Comment by wleoncio** [comment]
This is put on hold until the package is released; it's being deeply changed, so breakage with what has already been implemented is expected.

**Comment by wleoncio** [comment]
Package release, so development will continue. Connection of GUI to all package functions is enough to close this issue. Any bugs that may (inevitably) occur afterwards (e.g. buttons that don't work, failing modeling) should be handled by separate issues.
